### ISSUE TITLE
请问在哪里可以买到这本书呢？

### ISSUE THREAD

**Issue by fengqiangboy** [feicong/macbook#3]

**Comment by feicong** [comment]
京东：https://item.jd.com/12137171.html
亚马逊：https://www.amazon.cn/macOS%E8%BD%AF%E4%BB%B6%E5%AE%89%E5%85%A8%E4%B8%8E%E9%80%86%E5%90%91%E5%88%86%E6%9E%90-%E4%B8%B0%E7%94%9F%E5%BC%BA-%E9%82%A2%E4%BF%8A%E6%9D%B0/dp/B074323CHX/
互动出版社：http://product.china-pub.com/6170966

**Comment by fengqiangboy** [comment]
有没有出kindle版的计划呢？感觉电子书还是方便些
