### ISSUE TITLE
第五章勘误

### ISSUE THREAD

**Issue by Robin-Rhee** [feicong/macbook#6]
1.189页“字符串”一节“用于定义类似于C语言字符串字面量的的字符串”多了一个的字
2.191页图5-2下面的第二行文字的“REX”寄存器应为“RAX”寄存器
3.193页第10行助记符的英文错了，应为mnemonic
4.196页“5.4.5 栈操作指令”一节的第三行“这个区域分为两堆和栈个部分”应为“这个区域分为堆和栈两个部分”

**Comment by feicong** [comment]
https://github.com/feicong/macbook_issues
