### ISSUE TITLE
"Base64加密"这种说法不准确

### ISSUE THREAD

**Issue by Huang-Libo** [feicong/macbook#7]
P/20, 第二段最后面写道: "...进行Base64加密".

Base64 只能算是一种编码方式, 而不是加密.

参考链接:
https://zh.wikipedia.org/wiki/Base64
http://www.ruanyifeng.com/blog/2008/06/base64.html

**Comment by feicong** [comment]
提交issue可以到这里，https://github.com/feicong/macbook_issues
已改为编码。
